project('elma', 'c', 'cpp', version: '1.4', meson_version: '>=1.2.0', default_options: ['cpp_std=c++20'])

add_project_arguments('-DELMA_VERSION="@0@"'.format(meson.project_version()), language: 'cpp')

if get_option('buildtype') == 'debug' or get_option('buildtype') == 'debugoptimized'
    add_project_arguments('-DDEBUG', language: 'cpp')
endif

if get_option('profile_performance') == true
    add_project_arguments('-DPROFILE_PERFORMANCE', language: 'cpp')
endif

elma_sources = files(
    'src/debug/profiler.cpp',
    'src/editor/canvas.cpp',
    'src/editor/dialog.cpp',
    'src/editor/editor.cpp',
    'src/editor/help.cpp',
    'src/editor/screen_pic.cpp',
    'src/editor/tool.cpp',
    'src/editor/topology.cpp',
    'src/editor/window.cpp',
    'src/eol/battle.cpp',
    'src/eol/console.cpp',
    'src/eol/eol_table.cpp',
    'src/eol/eol.cpp',
    'src/eol/settings.cpp',
    'src/eol/status_messages.cpp',
    'src/game/driver.cpp',
    'src/game/fps.cpp',
    'src/game/game.cpp',
    'src/game/level_load.cpp',
    'src/game/qopen.cpp',
    'src/game/recorder.cpp',
    'src/game/state.cpp',
    'src/glad/glad.c',
    'src/level/level.cpp',
    'src/level/object.cpp',
    'src/level/polygon.cpp',
    'src/level/segments.cpp',
    'src/level/sprite.cpp',
    'src/log.cpp',
    'src/main.cpp',
    'src/menu/ball_collision.cpp',
    'src/menu/ball_handler.cpp',
    'src/menu/ball.cpp',
    'src/menu/best_times.cpp',
    'src/menu/controls.cpp',
    'src/menu/dialog.cpp',
    'src/menu/external.cpp',
    'src/menu/intro.cpp',
    'src/menu/main.cpp',
    'src/menu/nav.cpp',
    'src/menu/options.cpp',
    'src/menu/pic.cpp',
    'src/menu/play.cpp',
    'src/menu/player.cpp',
    'src/menu/rec_list.cpp',
    'src/menu/replay_cache.cpp',
    'src/menu/replay.cpp',
    'src/menu/skip.cpp',
    'src/physics/collision.cpp',
    'src/physics/flagtag.cpp',
    'src/physics/forces.cpp',
    'src/physics/init.cpp',
    'src/physics/move.cpp',
    'src/pic/abc8.cpp',
    'src/pic/anim.cpp',
    'src/pic/lgr.cpp',
    'src/pic/pic8.cpp',
    'src/pic/piclist.cpp',
    'src/pic/surface.cpp',
    'src/platform/sdl/gl_renderer.cpp',
    'src/platform/sdl/keyboard.cpp',
    'src/platform/sdl/scancode.cpp',
    'src/platform/sdl/sdl.cpp',
    'src/platform/text_input.cpp',
    'src/platform/utils.cpp',
    'src/renderer/affine.cpp',
    'src/renderer/canvas.cpp',
    'src/renderer/grass.cpp',
    'src/renderer/object_overlay.cpp',
    'src/renderer/render.cpp',
    'src/renderer/timer.cpp',
    'src/renderer/opengl/kuski.cpp',
    'src/renderer/opengl/painter.cpp',
    'src/renderer/opengl/utils.cpp',
    'src/renderer/opengl/texture_cache.cpp',
    'src/renderer/opengl/canvas.cpp',
    'src/renderer/opengl/background.cpp',
    'src/renderer/opengl/objects.cpp',
    'src/renderer/opengl/timer.cpp',
    'src/renderer/opengl/minimap.cpp',
    'src/renderer/opengl/console.cpp',
    'src/renderer/opengl/widget.cpp',
    'src/renderer/opengl/widget_text.cpp',
    'src/renderer/opengl/widget_text_ft.cpp',
    'src/renderer/opengl.cpp',
    'src/sound/engine.cpp',
    'src/sound/wav.cpp',
    'src/util/file_iter.cpp',
    'src/util/util.cpp',
    'src/util/stb_image.cpp',
    'src/vect2.cpp',
)

inc = include_directories('include')

cpp = meson.get_compiler('cpp')
link_args = []
cpp_args = []
deps = []

# Required for nlohmann_json on Apple clang < 12
if cpp.get_id() == 'clang' and cpp.version().version_compare('<12.0')
    add_project_arguments('-DJSON_HAS_CPP_17', language: 'cpp')
endif

win_subsystem = 'windows'
if cpp.get_id() == 'msvc'
    # Conforming preprocessor required for __VA_OPT__
    cpp_args += ['/Zc:preprocessor']

    if get_option('buildtype') == 'debug' or get_option('buildtype') == 'debugoptimized' or get_option('profile_performance') == true
        # Allows printf when debugging
        win_subsystem = 'console'
    endif

    if win_subsystem == 'windows'
        # Override windows subsystem entrypoint to main instead of WinMain
        link_args += ['/ENTRY:mainCRTStartup']
    endif
else
    cpp_args += ['-Wno-deprecated-declarations', '-Wunreachable-code']
endif

if get_option('no_freetype')            
  freetype_dep = []                     
else                                    
  freetype_dep = dependency('freetype2')
endif                                   

sdl2_dep = dependency('sdl2',
    static: build_machine.system() == 'windows' or get_option('static_sdl'),
    default_options: {
        'test': false,
        'with_main': false,
    }
)

gl_dep = dependency('gl', required: true)

nlohmann_json_dep = dependency('nlohmann_json')

deps += [nlohmann_json_dep, gl_dep, sdl2_dep, freetype_dep]

executable(
    'elma',
    elma_sources,
    include_directories: inc,
    cpp_args: cpp_args,
    link_args: link_args,
    dependencies: deps,
    win_subsystem: win_subsystem,
)
